// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwavktrxcheiewamtipn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3YXZrdHJ4Y2hlaWV3YW10aXBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxOTU0NzUsImV4cCI6MjA2ODc3MTQ3NX0.6V5ePybe1UuoqO_nNKP3PE29omK6mdCg8wgOgyhAbeM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});